version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ewallet_db
    restart: unless-stopped
    # Naik 2 folder untuk menemukan .env di root
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ewallet_net

  backend:
    container_name: ewallet_backend
    build:
      # Naik 2 folder agar Docker bisa membaca package.json root dan pnpm-workspace.yaml
      context: ../../
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - ewallet_net

  frontend:
    container_name: ewallet_frontend
    build:
      context: ../../
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - ewallet_net

volumes:
  pgdata:

networks:
  ewallet_net:
    driver: bridge
